import { useMemo } from 'react';

import { theme } from 'antd';
import type { ThemeConfig } from 'antd';

export const useThemeConfig = (appMode: 'light' | 'dark'): ThemeConfig => {
  return useMemo(() => {
    if (appMode === 'dark') {
      return {
        algorithm: theme.darkAlgorithm,
        cssVar: true,
        hashed: false,
        token: {
          colorPrimary: '#4f8cff',
          colorPrimaryHover: '#6da3ff',
          colorPrimaryActive: '#3d72e0',
          colorPrimaryBorder: '#316abc',
          colorPrimaryBorderHover: '#4f8cff',
          colorPrimaryBg: '#1a2332',
          colorPrimaryBgHover: '#1c314f',
          colorBgBase: '#1a1a1a',
          colorBgContainer: '#242424',
          colorBgElevated: '#2e2e2e',
          colorBgLayout: '#1a1a1a',
          colorBgSpotlight: '#333',
          colorBgMask: 'rgba(0, 0, 0, 0.55)',
          colorTextBase: 'rgba(255, 255, 255, 0.88)',
          colorTextSecondary: 'rgba(255, 255, 255, 0.55)',
          colorTextTertiary: 'rgba(255, 255, 255, 0.35)',
          colorTextQuaternary: 'rgba(255, 255, 255, 0.25)',
          colorBorder: '#4a4a4a',
          colorBorderSecondary: '#333',
          colorSuccess: '#5cb85c',
          colorWarning: '#d4a03c',
          colorError: '#e05555',
          colorInfo: '#4f8cff',
          colorSuccessBg: '#1e2a1e',
          colorWarningBg: '#2d2618',
          colorErrorBg: '#2e1c1e',
          colorInfoBg: '#1a2332',
          colorSuccessBorder: '#2d4a2d',
          colorWarningBorder: '#5c4a28',
          colorErrorBorder: '#5c2a2c',
          colorInfoBorder: '#2a4570',
          colorLink: '#6da3ff',
          colorLinkHover: '#8cb9ff',
          colorLinkActive: '#4f8cff',
          borderRadius: 6,
          borderRadiusLG: 8,
          borderRadiusSM: 4,
          borderRadiusXS: 2,
          boxShadow:
            '0 6px 16px 0 rgba(0, 0, 0, 0.50), 0 3px 6px -4px rgba(0, 0, 0, 0.55), 0 9px 28px 8px rgba(0, 0, 0, 0.45)',
          boxShadowSecondary:
            '0 6px 16px 0 rgba(0, 0, 0, 0.70), 0 3px 6px -4px rgba(0, 0, 0, 0.75), 0 9px 28px 8px rgba(0, 0, 0, 0.65)',
          boxShadowTertiary:
            '0 1px 2px 0 rgba(0, 0, 0, 0.45), 0 1px 6px -1px rgba(0, 0, 0, 0.35), 0 2px 4px 0 rgba(0, 0, 0, 0.30)',
        },
        components: {
          Layout: {
            headerBg: '#242424',
            headerColor: 'rgba(255, 255, 255, 0.88)',
            siderBg: '#1e1e1e',
            bodyBg: '#1a1a1a',
            footerBg: '#1a1a1a',
            triggerBg: '#2e2e2e',
            triggerColor: 'rgba(255, 255, 255, 0.55)',
          },
          Menu: {
            itemBg: '#1e1e1e',
            itemColor: 'rgba(255, 255, 255, 0.55)',
            itemHoverBg: 'rgba(255, 255, 255, 0.05)',
            itemHoverColor: 'rgba(255, 255, 255, 0.85)',
            itemSelectedBg: 'rgba(79, 140, 255, 0.12)',
            itemSelectedColor: '#6da3ff',
            itemActiveBg: 'rgba(79, 140, 255, 0.18)',
            popupBg: '#2e2e2e',
            subMenuItemBg: '#1e1e1e',
            groupTitleColor: 'rgba(255, 255, 255, 0.35)',
          },
          Table: {
            headerBg: '#222',
            headerColor: 'rgba(255, 255, 255, 0.85)',
            headerSortActiveBg: '#2a2a2a',
            headerSortHoverBg: '#2a2a2a',
            rowHoverBg: 'rgba(255, 255, 255, 0.03)',
            rowSelectedBg: 'rgba(79, 140, 255, 0.05)',
            rowSelectedHoverBg: 'rgba(79, 140, 255, 0.08)',
            borderColor: '#333',
            footerBg: '#1e1e1e',
            footerColor: 'rgba(255, 255, 255, 0.55)',
            cellPaddingBlock: 12,
            cellPaddingInline: 16,
          },
          Modal: {
            headerBg: '#2e2e2e',
            contentBg: '#2e2e2e',
            footerBg: '#2e2e2e',
            bodyPadding: 24,
          },
          Input: {
            hoverBorderColor: '#6da3ff',
            activeBorderColor: '#4f8cff',
            hoverBg: 'rgba(255, 255, 255, 0.06)',
            activeBg: 'rgba(255, 255, 255, 0.08)',
            addonBg: '#1e1e1e',
          },
          Select: {
            optionSelectedBg: 'rgba(79, 140, 255, 0.12)',
            optionActiveBg: 'rgba(255, 255, 255, 0.05)',
          },
          Tabs: {
            inkBarColor: '#4f8cff',
            itemHoverColor: '#6da3ff',
            itemSelectedColor: '#4f8cff',
            cardBg: '#1e1e1e',
          },
          Card: {
            headerBg: 'transparent',
          },
          Tag: {
            defaultBg: 'rgba(255, 255, 255, 0.06)',
            defaultColor: 'rgba(255, 255, 255, 0.65)',
          },
        },
      } as ThemeConfig;
    }
    return {
      algorithm: theme.defaultAlgorithm,
      cssVar: true,
      hashed: false,
      token: {
        colorPrimary: '#1677ff',
        colorPrimaryHover: '#4096ff',
        colorPrimaryActive: '#0958d9',
        colorPrimaryBorder: '#69b1ff',
        colorPrimaryBorderHover: '#4096ff',
        colorPrimaryBg: '#e6f4ff',
        colorPrimaryBgHover: '#bae0ff',
        colorBgBase: '#f5f5f5',
        colorBgContainer: '#fff',
        colorBgElevated: '#fff',
        colorBgLayout: '#f5f5f5',
        colorBgMask: 'rgba(0, 0, 0, 0.45)',
        colorTextBase: 'rgba(0, 0, 0, 0.88)',
        colorTextSecondary: 'rgba(0, 0, 0, 0.65)',
        colorTextTertiary: 'rgba(0, 0, 0, 0.45)',
        colorTextQuaternary: 'rgba(0, 0, 0, 0.25)',
        colorBorder: '#d9d9d9',
        colorBorderSecondary: '#f0f0f0',
        colorSuccess: '#52c41a',
        colorWarning: '#faad14',
        colorError: '#ff4d4f',
        colorInfo: '#1677ff',
        colorSuccessBg: '#f6ffed',
        colorWarningBg: '#fffbe6',
        colorErrorBg: '#fff2f0',
        colorInfoBg: '#e6f4ff',
        colorSuccessBorder: '#b7eb8f',
        colorWarningBorder: '#ffe58f',
        colorErrorBorder: '#ffccc7',
        colorInfoBorder: '#91caff',
        colorLink: '#1677ff',
        colorLinkHover: '#4096ff',
        colorLinkActive: '#0958d9',
        borderRadius: 6,
        borderRadiusLG: 8,
        borderRadiusSM: 4,
        borderRadiusXS: 2,
      },
      components: {
        Layout: {
          headerBg: '#fff',
          headerColor: 'rgba(0, 0, 0, 0.88)',
          siderBg: '#fff',
          bodyBg: '#f5f5f5',
          footerBg: '#f5f5f5',
          triggerBg: '#e8e8e8',
          triggerColor: 'rgba(0, 0, 0, 0.65)',
        },
        Menu: {
          itemBg: '#fff',
          itemColor: 'rgba(0, 0, 0, 0.65)',
          itemHoverBg: 'rgba(0, 0, 0, 0.04)',
          itemHoverColor: 'rgba(0, 0, 0, 0.88)',
          itemSelectedBg: 'rgba(0, 0, 0, 0.06)',
          itemSelectedColor: '#1677ff',
          itemActiveBg: 'rgba(0, 0, 0, 0.08)',
          popupBg: '#fff',
          subMenuItemBg: '#fff',
          groupTitleColor: 'rgba(0, 0, 0, 0.45)',
        },
        Table: {
          headerBg: '#fafafa',
          headerColor: 'rgba(0, 0, 0, 0.88)',
          headerSortActiveBg: '#f0f0f0',
          headerSortHoverBg: '#f0f0f0',
          rowHoverBg: 'rgba(0, 0, 0, 0.02)',
          rowSelectedBg: 'rgba(22, 119, 255, 0.04)',
          rowSelectedHoverBg: 'rgba(22, 119, 255, 0.08)',
          borderColor: '#f0f0f0',
          footerBg: '#fafafa',
          footerColor: 'rgba(0, 0, 0, 0.65)',
          cellPaddingBlock: 12,
          cellPaddingInline: 16,
        },
        Modal: {
          headerBg: '#fff',
          contentBg: '#fff',
          footerBg: '#fff',
          bodyPadding: 24,
        },
        Input: {
          hoverBorderColor: '#4096ff',
          activeBorderColor: '#1677ff',
          hoverBg: '#fff',
          activeBg: '#fff',
          addonBg: '#fafafa',
        },
        Select: {
          optionSelectedBg: 'rgba(22, 119, 255, 0.08)',
          optionActiveBg: 'rgba(0, 0, 0, 0.04)',
        },
        Tabs: {
          inkBarColor: '#1677ff',
          itemHoverColor: '#4096ff',
          itemSelectedColor: '#1677ff',
          cardBg: '#fafafa',
        },
        Card: {
          headerBg: 'transparent',
        },
        Tag: {
          defaultBg: '#fafafa',
          defaultColor: 'rgba(0, 0, 0, 0.65)',
        },
      },
    } as ThemeConfig;
  }, [appMode]);
};
